version: '3.9'

services:

  app:
    build:
      context: client
    container_name: e-documents-nuxt
    restart: always
    ports:
      - '4000:4000'
    environment:
      - HOST=0.0.0.0
    command: 'npm run start'
